---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudflinger-demo
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: httpapps.api.cloudflinger.com
spec:
  group: api.cloudflinger.com
  names:
    kind: HttpApp
    listKind: HttpAppList
    plural: httpapps
    singular: httpapp
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudflinger-operator
  namespace: cloudflinger-demo
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: cloudflinger-operator
  namespace: cloudflinger-demo
rules:
  - apiGroups:
    - ""
    resources:
    - pods
    - services
    - endpoints
    - persistentvolumeclaims
    - events
    - configmaps
    - secrets
    verbs:
    - '*'
  - apiGroups:
    - ""
    resources:
    - namespaces
    verbs:
    - get
  - apiGroups:
    - apps
    resources:
    - deployments
    - daemonsets
    - replicasets
    - statefulsets
    verbs:
    - '*'
  - apiGroups:
    - extensions
    resources:
    - ingresses
    verbs:
    - '*'
  - apiGroups:
    - monitoring.coreos.com
    resources:
    - servicemonitors
    verbs:
    - get
    - create
  - apiGroups:
    - apps
    resourceNames:
    - cloudflinger-operator
    resources:
    - deployments/finalizers
    verbs:
    - update
  - apiGroups:
    - api.cloudflinger.com
    resources:
    - '*'
    verbs:
    - '*'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cloudflinger-operator
  namespace: cloudflinger-demo
subjects:
- kind: ServiceAccount
  name: cloudflinger-operator
  # Replace this with the namespace the operator is deployed in.
  namespace: cloudflinger-demo
roleRef:
  kind: Role
  name: cloudflinger-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflinger-operator
  namespace: cloudflinger-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cloudflinger-operator
  template:
    metadata:
      labels:
        name: cloudflinger-operator
    spec:
      serviceAccountName: cloudflinger-operator
      containers:
        - name: app-operator
          # Replace this with the built image name
          image: cloudflinger/app-operator
          command:
          - app-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: "cloudflinger-demo"
            - name: CLOUDFLINGER_KEY
              value: heritage
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "app-operator"
          resources:
            limits:
              cpu: 500m
              memory: "512Mi"
            limits:
              cpu: 250m
              memory: "50Mi"
---
