apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: httpapps.api.cloudflinger.com
spec:
  group: api.cloudflinger.com
  names:
    kind: HttpApp
    listKind: HttpAppList
    plural: httpapps
    singular: httpapp
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
